# Generated by Django 3.0.7 on 2020-06-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=80)),
                ('shortName', models.CharField(max_length=30)),
                ('continent', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='DATE')),
                ('total_case', models.FloatField(blank=True, null=True)),
                ('new_case', models.FloatField(blank=True, null=True)),
                ('total_death', models.FloatField(blank=True, null=True)),
                ('new_death', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
