# Generated by Django 3.0.7 on 2020-06-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
