# Generated by Django 3.0.7 on 2020-07-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0003_auto_20200707_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('date', models.DateField(verbose_name='DATE')),
                ('confirm_img', models.FileField(null=True, upload_to='images/confirmed', verbose_name='')),
                ('daily_img', models.FileField(null=True, upload_to='images/daily', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='confirm_img',
        ),
        migrations.RemoveField(
            model_name='country',
            name='daily_img',
        ),
    ]
