# Generated by Django 3.0.7 on 2020-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0004_auto_20200708_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysituation',
            name='confirm_img',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysituation',
            name='daily_img',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
