# Generated by Django 3.0.7 on 2020-07-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0005_auto_20200708_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysituation',
            name='confirm_img',
            field=models.ImageField(default='con.png', upload_to='image/confirm'),
        ),
        migrations.AlterField(
            model_name='dailysituation',
            name='daily_img',
            field=models.ImageField(default='daily.png', upload_to='image/daily'),
        ),
    ]
