# Generated by Django 3.0.7 on 2020-07-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0006_auto_20200709_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysituation',
            name='daily_img',
        ),
    ]
