# Generated by Django 3.0.7 on 2020-07-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0008_auto_20200709_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysituation',
            name='daily_img',
            field=models.ImageField(default='daily.png', upload_to='images/daily'),
        ),
        migrations.AlterField(
            model_name='dailysituation',
            name='confirm_img',
            field=models.ImageField(default='con.png', upload_to='images/confirm'),
        ),
    ]
