# Generated by Django 3.0.7 on 2020-07-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0009_auto_20200709_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysituation',
            name='confirm_img',
            field=models.ImageField(default='con.png', upload_to='images/confirm/'),
        ),
        migrations.AlterField(
            model_name='dailysituation',
            name='daily_img',
            field=models.ImageField(default='daily.png', upload_to='images/daily/'),
        ),
    ]
