# Generated by Django 3.0.7 on 2020-07-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyUpdate', '0011_auto_20200709_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysituation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysituation',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
